### ISSUE TITLE
Design Tokenizer

### ISSUE THREAD

**Issue by teddyknox** [duality-labs/duality#179]
Required for transfer swap and forward.

**Comment by itamarreif** [comment]
[Initial spec draft](https://www.notion.so/dualityxyz/spec-draft-dd3994bd24e149dfa45066ce40566bc6)

Following the [issues](https://www.notion.so/dualityxyz/spec-draft-dd3994bd24e149dfa45066ce40566bc6#7360c818183449e398434f7ada2995ce) encountered while designing a tokenizer that enforces a distribution over deposits, the decision was made to abandon the idea and instead go for the minimal viable tokenizer.

The simplest implementation would be to simply mint a token that corresponds to the pool shares allocated to users upon deposit and burn the relevant shares upon withdrawal.

Tentatively, this can be implemented as a pair of hook functions that are called by the [msgServer](https://github.com/duality-labs/duality/blob/main/x/dex/keeper/msg_server.go) using return values from [DepositCore](https://github.com/duality-labs/duality/blob/main/x/dex/keeper/core.go#L15) and [WithdrawCore](https://github.com/duality-labs/duality/blob/main/x/dex/keeper/core.go#L169).

Requirements:
- [ ] DepositCore and WithdrawCore should return an array of successes and failures. In case that the currently ongoing refactor ends up in changing those interfaces to only conduct one operation rather than an array, then the return value would need to correspond to the success or failure of that specific deposit or withdrawal.
- [ ] Two functions along the lines DepositTokenizer and WithdrawTokenizer that would mint and burn a token corresponding to the amount of shares minted or burned, respectively, using the [BankKeeper](https://docs.cosmos.network/v0.45/modules/bank/02_keepers.html#)'s MintCoins and BurnCoins methods.

**Comment by itamarreif** [comment]
An extension to the above idea that was floating in the design meeting is to tokenize a collection of positions, i.e. across multiple pools. This could be implemented as a "fractionalized NFT", i.e. a new fungible token denomination for each position that allows users to compose a position in the form of a fungible, ERC20-style token.

To accommodate multiple pools in one position, metadata will need to be stored for each pool and getters for calculating value/token amounts across different pools will be needed.

**Comment by itamarreif** [comment]
- [ ] DepositCore and WithdrawCore should return an array of successes and failures. In case that the currently ongoing refactor ends up in changing those interfaces to only conduct one operation rather than an array, then the return value would need to correspond to the success or failure of that specific deposit or withdrawal.
- [ ] Two functions along the lines DepositTokenizer and WithdrawTokenizer that would mint and burn a token corresponding to the amount of shares minted or burned, respectively, using the [BankKeeper](https://docs.cosmos.network/v0.45/modules/bank/02_keepers.html#)'s MintCoins and BurnCoins methods.
- [ ] Add two endpoints to the [msgServer](https://github.com/duality-labs/duality/blob/main/x/dex/keeper/msg_server.go) that would run a series of deposits or withdrawals and mint/burn tokens respectively.
- [ ] getters for calculating the makeup of the underlying assets of the position.
    - [ ] tokens in term of token A
    - [ ] tokens in term of token B
    - [ ] tokens in term of token A, B
    - still need to take a closer look at e.g. Agoric resources to design this part more carefully

**Comment by itamarreif** [comment]
[Finalized design document](https://www.notion.so/dualityxyz/Design-Document-Single-Pool-Share-Tokenizer-68cba941fef24ababab74d4dac23dca8)
